remote_theme: thelehhman/plainwhite-jekyll
plainwhite:
  name: Ani Bharadwaj
  tagline: Developer
  date_format: "%b %-d, %Y"
  
  social_links: 
    instagram: __ani._.b__
    github: themartian117
  navigation:
    -title: Home
     url: "https://themartian117.github.io/blog"

    
    
   
