remote_theme: thelehhman/plainwhite-jekyll
plainwhite:
  name: Adam Denisov
  tagline: Developer. Designer
  date_format: "%b %-d, %Y"

plainwhite:
  navigation:
    - title: Post 1
      url: "/post1"

    
    
   
